name: croco
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mysql1: ^0.20.0
  palette_generator: ^0.3.3+2
  tmdb_api: ^2.1.4
  url_launcher: ^6.1.6
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_slider: ^4.1.1
  flutter_lints: ^2.0.0
  flutter_cache_manager: ^3.3.0
  m3u: ^1.0.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
